sonar.projectKey=rac-rutasdeentrega
sonar.projectName=rac-rutasdeentrega
sonar.projectVersion=1.0

sonar.sources=apps

sonar.sourceEncoding=UTF-8

sonar.inclusions=**/*.py
sonar.exclusions=**/migrations/**,**/__pycache__/**,**/venv/**,**/env/**,**/*.pyc,**/node_modules/**,**/static/**,**/tests.py