# Generated by Django 6.0.2 on 2026-04-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('companies', '0001_initial'),
        ('users', '0003_alter_user_managers_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['admin', 'company'])), name='user_role_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('company__isnull', True), ('role', 'admin')), models.Q(('company__isnull', False), ('role', 'company')), _connector='OR'), name='user_role_company_consistency'),
        ),
    ]
