# Generated by Django 6.0.2 on 2026-04-18 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_count', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('error', 'Error')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='companies.company')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='warehouses.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('sequence_order', models.IntegerField(blank=True, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_points', to='deliveries.route')),
            ],
        ),
        migrations.CreateModel(
            name='RouteInputFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='routes/')),
                ('file_type', models.CharField(choices=[('json', 'JSON'), ('csv', 'CSV')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('route', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='input_file', to='deliveries.route')),
            ],
        ),
        migrations.CreateModel(
            name='RouteSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_distance', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='deliveries.route')),
            ],
        ),
        migrations.CreateModel(
            name='RouteSolutionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.IntegerField()),
                ('delivery_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveries.deliverypoint')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='deliveries.routesolution')),
            ],
        ),
    ]
