# Generated by Django 6.0.2 on 2026-04-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='k_opt',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
