# Generated by Django 6.0.2 on 2026-04-13 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliveries', '0001_initial'),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='warehouses.warehouse'),
        ),
        migrations.AddField(
            model_name='deliverypoint',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_points', to='deliveries.route'),
        ),
        migrations.AddField(
            model_name='routeinputfile',
            name='route',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='input_file', to='deliveries.route'),
        ),
        migrations.AddField(
            model_name='routesolution',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='deliveries.route'),
        ),
        migrations.AddField(
            model_name='routesolutiondetail',
            name='delivery_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveries.deliverypoint'),
        ),
        migrations.AddField(
            model_name='routesolutiondetail',
            name='solution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='deliveries.routesolution'),
        ),
    ]
