# Generated by Django 6.0.2 on 2026-04-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_route_k_opt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routeinputfile',
            name='file_type',
            field=models.CharField(choices=[('json', 'JSON'), ('csv', 'CSV'), ('xlsx', 'XLSX')], max_length=10),
        ),
    ]
