# Generated by Django 6.0.2 on 2026-04-18 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_alter_routeinputfile_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypoint',
            name='package_quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliverypoint',
            name='receiver_name',
            field=models.CharField(default='cesarin', max_length=255),
            preserve_default=False,
        ),
    ]
