# Generated by Django 6.0.2 on 2026-04-18 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0004_deliverypoint_package_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverypoint',
            name='sequence_order',
        ),
    ]
