# Generated by Django 6.0.2 on 2026-04-18 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('endpoint', models.CharField(blank=True, max_length=500)),
                ('action', models.CharField(choices=[('create', 'Creación'), ('read', 'Consulta'), ('update', 'Actualización'), ('delete', 'Eliminación')], max_length=10)),
                ('object_id', models.CharField(max_length=255)),
                ('object_repr', models.CharField(max_length=500)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Entrada de bitácora',
                'verbose_name_plural': 'Bitácora',
                'ordering': ['-timestamp'],
            },
        ),
    ]
