"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.
"""

from datetime import timedelta
import os
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv
from loguru import logger

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent
load_dotenv(BASE_DIR / ".env")

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY") or os.getenv("SECRET_KEY")
if not SECRET_KEY:
    settings_module = os.getenv("DJANGO_SETTINGS_MODULE", "")
    if settings_module.endswith(".dev"):
        # Local fallback only for development convenience.
        SECRET_KEY = "dev-only-insecure-secret-key-change-for-prod"
    else:
        raise ImproperlyConfigured("DJANGO_SECRET_KEY or SECRET_KEY must be set.")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").lower() == "true"

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'corsheaders',
    'rest_framework',
    'drf_spectacular',
    'rest_framework_simplejwt.token_blacklist',
    'django_q',

    'apps.administration',
    'apps.authorization',
    'apps.companies',
    'apps.deliveries',
    'apps.warehouses',
    'apps.users',
    'apps.audit',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'config.middleware.RequestLoggingMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    "apps.audit.middleware.AuditMiddleware",
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME', 'rac_db'),
        'USER': os.getenv('DB_USER', 'rac_user'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'root'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '3306'),
    }
}

# Password validation

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'users.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'login': os.getenv('LOGIN_THROTTLE_RATE', '3/min'),
    },
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    "DEFAULT_RENDERER_CLASSES": [
        "config.renderers.ApiResponseRenderer",
    ],
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'RAC Rutas de Entrega API',
    'DESCRIPTION': 'API para la administración de rutas de entrega, empresas, almacenes y entregas.',
    'VERSION': '1.0.0',
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=10),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
}

# Internationalization

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)

STATIC_URL = 'static/'


def _env_list(name, default=None):
    value = os.getenv(name, "")
    if not value:
        return default or []
    return [item.strip() for item in value.split(",") if item.strip()]

ALLOWED_HOSTS = _env_list('ALLOWED_HOSTS', [])
CORS_ALLOWED_ORIGINS = _env_list('CORS_ALLOWED_ORIGINS', ['http://localhost:3000'])
CORS_ALLOW_ALL_ORIGINS = False

NOMINATIM_USER_AGENT = "route-optimization-app"

LOGGING_CONFIG = None

LOGURU_LOGGINS = {
    "handlers": [
        {
            "sink": BASE_DIR / "logs/debug.log",
            "level": "DEBUG",
            "filter": lambda r: r["level"].name == "DEBUG",
            "format": "{time:YYYY-MM-DD HH:mm:ss} | {level:<8} | {name}:{function}:{line} - {message}",
            "rotation": "10 MB",
            "retention": "7 days",
            "compression": "zip",
        },
        {
            "sink": BASE_DIR / "logs/info.log",
            "level": "INFO",
            "filter": lambda r: r["level"].name == "INFO",
            "format": "{time:YYYY-MM-DD HH:mm:ss} | {level:<8} | {name}:{function}:{line} - {message}",
            "rotation": "10 MB",
            "retention": "7 days",
            "compression": "zip",
        },
        {
            "sink": BASE_DIR / "logs/warning.log",
            "level": "WARNING",
            "filter": lambda r: r["level"].name == "WARNING",
            "format": "{time:YYYY-MM-DD HH:mm:ss} | {level:<8} | {name}:{function}:{line} - {message}",
            "rotation": "10 MB",
            "retention": "7 days",
            "compression": "zip",
        },
        {
            "sink": BASE_DIR / "logs/error.log",
            "level": "ERROR",
            "filter": lambda r: r["level"].name == "ERROR",
            "format": "{time:YYYY-MM-DD HH:mm:ss} | {level:<8} | {name}:{function}:{line} - {message}",
            "rotation": "10 MB",
            "retention": "7 days",
            "compression": "zip",
            "backtrace": True,
            "diagnose": True,
        },
        {
            "sink": BASE_DIR / "logs/critical.log",
            "level": "CRITICAL",
            "filter": lambda r: r["level"].name == "CRITICAL",
            "format": "{time:YYYY-MM-DD HH:mm:ss} | {level:<8} | {name}:{function}:{line} - {message}",
            "rotation": "10 MB",
            "retention": "7 days",
            "compression": "zip",
            "backtrace": True,
            "diagnose": True,
        },
    ]
}

logger.configure(**LOGURU_LOGGINS)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {"loguru": {"class": "config.interceptor.InterceptorHandler"}},
    "root": {"handlers": ["loguru"], "level": "DEBUG"},
}

Q_CLUSTER = {
    'name': 'myproject',
    'workers': 4,
    'timeout': 90,
    'retry': 120,
    'queue_limit': 50,
    'bulk': 10,
    'orm': 'default'
}

# Configuración para el servicio de correo de Google Cloud
EMAIL_BACKEND = 'utils.gmail_backend.GmailBackend'
DEFAULT_FROM_EMAIL = os.getenv('GOOGLE_EMAIL_USER', 'noreply@example.com')

# Configuración de URL del frontend
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:3000')