# Generated by Django 6.0.2 on 2026-04-13 04:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='El nombre solo puede contener letras, números y los caracteres: - . , # y debe tener entre 2 y 255 caracteres', regex='^[a-zA-ZáéíóúÁÉÍÓÚüÜñÑ0-9\\s\\-\\.\\,\\#]{2,255}$')])),
                ('address', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='La dirección solo puede contener letras, números y los caracteres: - . , # / y debe tener entre 5 y 255 caracteres', regex='^[a-zA-ZáéíóúÁÉÍÓÚüÜñÑ0-9\\s\\-\\.\\,\\#\\/]{5,255}$')])),
                ('city', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='El campo solo puede contener letras y debe tener entre 2 y 100 caracteres', regex='^[a-zA-ZáéíóúÁÉÍÓÚüÜñÑ\\s\\-\\.]{2,100}$')])),
                ('state', models.CharField(choices=[('Aguascalientes', 'Aguascalientes'), ('Baja California', 'Baja California'), ('Baja California Sur', 'Baja California Sur'), ('Campeche', 'Campeche'), ('Chiapas', 'Chiapas'), ('Chihuahua', 'Chihuahua'), ('Ciudad de México', 'Ciudad de México'), ('Coahuila', 'Coahuila'), ('Colima', 'Colima'), ('Durango', 'Durango'), ('Guanajuato', 'Guanajuato'), ('Guerrero', 'Guerrero'), ('Hidalgo', 'Hidalgo'), ('Jalisco', 'Jalisco'), ('México', 'México'), ('Michoacán', 'Michoacán'), ('Morelos', 'Morelos'), ('Nayarit', 'Nayarit'), ('Nuevo León', 'Nuevo León'), ('Oaxaca', 'Oaxaca'), ('Puebla', 'Puebla'), ('Querétaro', 'Querétaro'), ('Quintana Roo', 'Quintana Roo'), ('San Luis Potosí', 'San Luis Potosí'), ('Sinaloa', 'Sinaloa'), ('Sonora', 'Sonora'), ('Tabasco', 'Tabasco'), ('Tamaulipas', 'Tamaulipas'), ('Tlaxcala', 'Tlaxcala'), ('Veracruz', 'Veracruz'), ('Yucatán', 'Yucatán'), ('Zacatecas', 'Zacatecas')], max_length=50)),
                ('country', models.CharField(default='México', editable=False, max_length=50)),
                ('postal_code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='El código postal debe contener exactamente 5 dígitos numéricos', regex='^\\d{5}$')])),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(14.5, message='Latitud fuera del territorio mexicano'), django.core.validators.MaxValueValidator(32.7, message='Latitud fuera del territorio mexicano')])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-118.4, message='Longitud fuera del territorio mexicano'), django.core.validators.MaxValueValidator(-86.7, message='Longitud fuera del territorio mexicano')])),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='companies.company')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('country', 'México')), name='warehouse_country_mexico'), models.CheckConstraint(condition=models.Q(('state__in', ['Aguascalientes', 'Baja California', 'Baja California Sur', 'Campeche', 'Chiapas', 'Chihuahua', 'Ciudad de México', 'Coahuila', 'Colima', 'Durango', 'Guanajuato', 'Guerrero', 'Hidalgo', 'Jalisco', 'México', 'Michoacán', 'Morelos', 'Nayarit', 'Nuevo León', 'Oaxaca', 'Puebla', 'Querétaro', 'Quintana Roo', 'San Luis Potosí', 'Sinaloa', 'Sonora', 'Tabasco', 'Tamaulipas', 'Tlaxcala', 'Veracruz', 'Yucatán', 'Zacatecas'])), name='warehouse_state_valid'), models.CheckConstraint(condition=models.Q(models.Q(('latitude__isnull', True), ('longitude__isnull', True)), models.Q(('latitude__isnull', False), ('longitude__isnull', False)), _connector='OR'), name='warehouse_coordinates_complete'), models.CheckConstraint(condition=models.Q(('latitude__isnull', True), ('latitude__gte', 14.5), _connector='OR'), name='warehouse_latitude_min'), models.CheckConstraint(condition=models.Q(('latitude__isnull', True), ('latitude__lte', 32.7), _connector='OR'), name='warehouse_latitude_max'), models.CheckConstraint(condition=models.Q(('longitude__isnull', True), ('longitude__gte', -118.4), _connector='OR'), name='warehouse_longitude_min'), models.CheckConstraint(condition=models.Q(('longitude__isnull', True), ('longitude__lte', -86.7), _connector='OR'), name='warehouse_longitude_max')],
            },
        ),
    ]
